### ISSUE TITLE
Redo flier selection

### ISSUE THREAD

**Issue by JakeDarling** [JakeDarling/magicflight#16]
Flier selection is confusing and boring. We need to sex it up. Here's a quick mockup. Feel free to tweak.
![flierselection](https://cloud.githubusercontent.com/assets/5066132/5333795/b552165a-7e50-11e4-8c0c-6801c59d8652.PNG)

**Comment by DeanTuesday** [comment]
I like this. Never saw until today

**Comment by DeanTuesday** [comment]
This is pretty much done. Although I will be adding more to this over time, the main issues are now fixed.
